version: '3.8'

services:
  yolov8-training:
    build:
      context: .
      dockerfile: Dockerfile  
    working_dir: /app  
    volumes:
      - ./training_data:/app/training_data  
      - ./output:/app/output 
      - C:/Users/Matthew/Desktop/Yolov8_mobile_app-main/train.py:/app/train.py
    environment:
      - PYTHONUNBUFFERED=1
